### ISSUE TITLE
"Redirect URI" missing in the step-by-step instructions, error AADSTS50011 after sign in

### ISSUE THREAD

**Issue by laikoni** [microsoftgraph/console-csharp-connect-sample#6]
Step 3 under _Register the application_ says:

> On the application registration page, select Add Platform. Select the Native App tile and save your change.

However, there is also a _Redirect URI_ required to register the application. The promt says:
 
> The URI to which Microsoft Azure AD will redirect in response to an OAuth 2.0 request. The value does not need to be a physical endpoint, but must be a valid URI.

The only info I found on this was [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code):

> For Native Applications provide a Redirect URI, which Azure AD will use to return token responses. Enter a value specific to your application, .e.g `http://MyFirstAADApp`

After doing so, when I run the code, enter my credentials and grant the permissions, the following error occurs: 

`AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '<client id>'`.

First of all, it would be nice to include what to use as Redirect URI in the instructions. 

Second, is this error related to the URI? Any ideas how to resolve it?

**Comment by AtDH01** [comment]
I'm having the same issue, tried both native app and web / api app.  I receive the same error message as yourself.

**Comment by AtDH01** [comment]
Ok - I got this working by registering the app via: https://apps.dev.microsoft.com/ rather than directly through the Azure AD Portal.  Be sure to select Native app.

**Comment by laikoni** [comment]
@AtDH01 https://apps.dev.microsoft.com/ is the page linked in the description, so I already tried it. However, I found out this site looks different depending on your account. With my company user account I get this: 
![apprepo01](https://user-images.githubusercontent.com/23499430/49719951-f3ab1100-fc5e-11e8-9481-06da119ecdd5.PNG)

Whereas a test account sees this:
![apprepo02](https://user-images.githubusercontent.com/23499430/49720004-0887a480-fc5f-11e8-8937-9ff5e575a66c.PNG)

Adding an app now worked with the latter as it automatically creates a reply URL, though it does not work with the former if you don't know how such a reply URL needs to look.

**Comment by AlanPBourke** [comment]
The Application Registration Portal link now redirects to this:

![2019-03-12 12_26_09-My Applications](https://user-images.githubusercontent.com/25082842/54200013-2fee4780-44c2-11e9-99ac-abd4f2f12264.png)

No hints about which option to choose, so I chose the first and completed the app registration. Back in Visual Studio, running the application gives this:

![2019-03-12 12_31_45-console-csharp-connect-sample (Running) - Microsoft Visual Studio](https://user-images.githubusercontent.com/25082842/54200465-5eb8ed80-44c3-11e9-94a8-3620da1ea5a0.png)


I don't want it to be multi-tenant, but I'll set it that way since it's an example. Doing that and retrying gives this:

![3](https://user-images.githubusercontent.com/25082842/54200366-21ecf680-44c3-11e9-9fac-a35946616bab.png)

So this example is useless at the time of writing.

**Comment by ypcode** [comment]
Hi,

 since, the apps.dev.microsoft.com is no longer supported by this time. I took a look at what the new registration portal under Azure portal does. And for console apps, it looks like it does not include one needed redirect URI : **urn:ietf:wg:oauth:2.0:oob**

Simply add it to the redirect URIs will solve the issue :)

Regards,
Yannick

**Comment by mjohl** [comment]
I added the URI manually in the portal and the authentication is now resolved for me.

![image](https://user-images.githubusercontent.com/4193377/57862512-601ed300-77f0-11e9-99ea-52174b6a5acc.png)

**Comment by jasonjoh** [comment]
Thanks for your interest in Microsoft Graph! We are archiving this sample, so I'm closing this issue. For a replacement C# console app sample, please see https://github.com/microsoftgraph/msgraph-training-dotnet-core. We apologize for any inconvenience.
